"""
Seed data for HealthyEye medicine database.
This is a starter set of ~40 common OTC/prescription salts sold in India.
Expand this list over time — it's the core IP of the product.

IMPORTANT: This data is for informational/demo purposes only. Before any
real-world use, every entry should be reviewed against an authoritative
source (e.g. CDSCO, package insert / product literature, or a pharmacist)
since incorrect medical info here is genuinely dangerous.
"""

seed_database = [
    {
        "salt_name": "Paracetamol",
        "aliases": ["Acetaminophen", "Paracetamol 500mg", "Paracetamol 650mg"],
        "common_brands": "Crocin, Dolo 650, Calpol",
        "used_for": "Fever, body pain, headache, mild pain relief",
        "category": "Pain relief / Fever",
        "timing": "After food, can repeat every 4-6 hours if needed",
        "avoid": "Don't combine with other paracetamol-containing medicines (risk of overdose). Avoid alcohol.",
        "precautions": "If fever lasts more than 3 days or exceeds 103°F, see a doctor.",
        "home_remedy": "Tulsi-ginger kadha, cold compress on forehead, plenty of fluids",
    },
    {
        "salt_name": "Cetirizine",
        "aliases": ["Cetirizine Hydrochloride"],
        "common_brands": "Cetrizine, Alerid, Okacet",
        "used_for": "Allergy, runny nose, itching, cold symptoms",
        "category": "Antihistamine / Allergy",
        "timing": "Preferably at night — can cause drowsiness",
        "avoid": "Avoid driving or operating machinery after taking it. Avoid alcohol.",
        "precautions": "Use caution in elderly patients or those with kidney issues.",
        "home_remedy": "Steam inhalation, warm saline gargle",
    },
    {
        "salt_name": "Amoxicillin",
        "aliases": ["Amoxicillin Trihydrate"],
        "common_brands": "Novamox, Mox, Amoxil",
        "used_for": "Bacterial infections (throat, chest, urinary tract, etc.)",
        "category": "Antibiotic",
        "timing": "As prescribed, usually every 8-12 hours, with or without food",
        "avoid": "Do not stop early even if you feel better — complete the full course.",
        "precautions": "Antibiotics should only be taken as prescribed by a doctor, not self-started. Tell your doctor if you're allergic to penicillin.",
        "home_remedy": None,
    },
    {
        "salt_name": "Domperidone",
        "aliases": [],
        "common_brands": "Domstal, Vomistop",
        "used_for": "Nausea, vomiting, bloating",
        "category": "Anti-nausea",
        "timing": "30 minutes before meals",
        "avoid": "Avoid in heart conditions without doctor's advice.",
        "precautions": "Consult a doctor if vomiting persists beyond a day or is accompanied by severe pain.",
        "home_remedy": "Ginger tea, lemon water in small sips",
    },
    {
        "salt_name": "Ibuprofen",
        "aliases": [],
        "common_brands": "Brufen, Combiflam (with paracetamol)",
        "used_for": "Pain, inflammation, fever",
        "category": "Pain relief / Anti-inflammatory (NSAID)",
        "timing": "After food, never on empty stomach",
        "avoid": "Avoid if you have stomach ulcers, asthma, or kidney issues. Avoid alcohol.",
        "precautions": "Not recommended for long-term daily use without medical supervision.",
        "home_remedy": "Warm compress for muscular pain, turmeric milk",
    },
    {
        "salt_name": "Omeprazole",
        "aliases": [],
        "common_brands": "Omez, Ocid",
        "used_for": "Acidity, heartburn, acid reflux, stomach ulcers",
        "category": "Antacid (Proton Pump Inhibitor)",
        "timing": "Empty stomach, 30 minutes before breakfast",
        "avoid": "Avoid spicy/oily food while on this medicine for best effect.",
        "precautions": "Long-term use should be under doctor supervision.",
        "home_remedy": "Cold milk, avoid lying down right after meals",
    },
    {
        "salt_name": "Metformin",
        "aliases": [],
        "common_brands": "Glycomet, Glucophage",
        "used_for": "Type 2 diabetes — controls blood sugar",
        "category": "Anti-diabetic",
        "timing": "With or right after meals to reduce stomach upset",
        "avoid": "Avoid alcohol. Don't skip meals after taking it (risk of low sugar).",
        "precautions": "Requires regular blood sugar monitoring; only take as prescribed.",
        "home_remedy": None,
    },
    {
        "salt_name": "Azithromycin",
        "aliases": [],
        "common_brands": "Azithral, Zithromax",
        "used_for": "Bacterial infections (respiratory, throat, skin)",
        "category": "Antibiotic",
        "timing": "Once daily, 1 hour before or 2 hours after food",
        "avoid": "Complete the full course even if symptoms improve early.",
        "precautions": "Only take as prescribed by a doctor.",
        "home_remedy": None,
    },
    {
        "salt_name": "Diclofenac",
        "aliases": [],
        "common_brands": "Voveran, Volini (gel form)",
        "used_for": "Muscle pain, joint pain, sprains, inflammation",
        "category": "Pain relief / Anti-inflammatory (NSAID)",
        "timing": "After food",
        "avoid": "Avoid in stomach ulcers, kidney disease. Avoid alcohol.",
        "precautions": "Not for long-term daily use without medical advice.",
        "home_remedy": "Warm oil massage, hot water fomentation",
    },
    {
        "salt_name": "Levocetirizine",
        "aliases": [],
        "common_brands": "Levocet, Xyzal",
        "used_for": "Allergies, cold, itching, sneezing",
        "category": "Antihistamine / Allergy",
        "timing": "At night — can cause drowsiness",
        "avoid": "Avoid driving after taking. Avoid alcohol.",
        "precautions": "Use caution in elderly or those with kidney issues.",
        "home_remedy": "Steam inhalation, warm fluids",
    },
    {
        "salt_name": "Pantoprazole",
        "aliases": [],
        "common_brands": "Pantop, Pan-D",
        "used_for": "Acidity, GERD, stomach ulcers",
        "category": "Antacid (Proton Pump Inhibitor)",
        "timing": "Empty stomach, before breakfast",
        "avoid": "Avoid spicy and oily food.",
        "precautions": "Long-term use should be monitored by a doctor.",
        "home_remedy": "Cold milk, small frequent meals",
    },
    {
        "salt_name": "Ondansetron",
        "aliases": [],
        "common_brands": "Emeset, Vomikind",
        "used_for": "Severe nausea and vomiting",
        "category": "Anti-nausea",
        "timing": "As directed, usually before meals or as needed",
        "avoid": "Avoid self-medicating for prolonged vomiting — see a doctor.",
        "precautions": "Seek medical attention if vomiting is severe, bloody, or persistent.",
        "home_remedy": "Ginger, small sips of water/ORS",
    },
    {
        "salt_name": "Amlodipine",
        "aliases": [],
        "common_brands": "Amlopres, Amlogard",
        "used_for": "High blood pressure (hypertension)",
        "category": "Blood pressure medicine",
        "timing": "Same time every day, with or without food",
        "avoid": "Avoid grapefruit juice. Don't stop suddenly without doctor's advice.",
        "precautions": "Regular BP monitoring recommended.",
        "home_remedy": None,
    },
    {
        "salt_name": "Loratadine",
        "aliases": [],
        "common_brands": "Loratin, Alaspan",
        "used_for": "Allergies, hay fever, itching (less drowsy option)",
        "category": "Antihistamine / Allergy",
        "timing": "Once daily, any time",
        "avoid": "Avoid alcohol.",
        "precautions": "Generally causes less drowsiness than cetirizine.",
        "home_remedy": "Steam inhalation",
    },
    {
        "salt_name": "Ranitidine",
        "aliases": [],
        "common_brands": "Rantac, Zinetac",
        "used_for": "Acidity, heartburn",
        "category": "Antacid",
        "timing": "Before meals or at bedtime",
        "avoid": "Note: Ranitidine has faced regulatory restrictions in some countries — check current availability/advice.",
        "precautions": "Consult a pharmacist about current status of this medicine.",
        "home_remedy": "Cold milk, avoid spicy food",
    },
    {
        "salt_name": "Aceclofenac",
        "aliases": [],
        "common_brands": "Zerodol, Aceclo",
        "used_for": "Pain, inflammation, arthritis, muscle pain",
        "category": "Pain relief / Anti-inflammatory (NSAID)",
        "timing": "After food",
        "avoid": "Avoid in ulcers, kidney disease. Avoid alcohol.",
        "precautions": "Not for long-term use without supervision.",
        "home_remedy": "Warm compress, gentle massage",
    },
    {
        "salt_name": "Cough Syrup - Dextromethorphan",
        "aliases": ["Dextromethorphan"],
        "common_brands": "Benadryl DR, Ascoril",
        "used_for": "Dry cough suppression",
        "category": "Cough syrup",
        "timing": "As directed, usually 2-3 times a day",
        "avoid": "Avoid combining with other cough/cold medicines (duplicate ingredients). Avoid alcohol.",
        "precautions": "Not recommended for young children without doctor's advice.",
        "home_remedy": "Honey-ginger mixture, warm turmeric milk, steam inhalation",
    },
    {
        "salt_name": "ORS (Oral Rehydration Salts)",
        "aliases": ["Electral"],
        "common_brands": "Electral, ORSL",
        "used_for": "Dehydration from diarrhea, vomiting, excessive sweating",
        "category": "Rehydration",
        "timing": "Small sips frequently throughout the day",
        "avoid": "Follow the mixing ratio on the packet exactly — don't over-concentrate.",
        "precautions": "Seek medical help if diarrhea persists beyond 2 days or shows blood.",
        "home_remedy": "Homemade ORS: 1L clean water + 6 tsp sugar + 1/2 tsp salt",
    },
    {
        "salt_name": "Multivitamin",
        "aliases": ["Vitamin B Complex", "Multivitamin Tablet"],
        "common_brands": "Becosules, Revital",
        "used_for": "General weakness, nutritional supplement",
        "category": "Supplement",
        "timing": "After food, morning preferred",
        "avoid": "Not a substitute for a balanced diet.",
        "precautions": "Consult a doctor before long-term use, especially with existing conditions.",
        "home_remedy": "Balanced diet with fruits, seasonal vegetables",
    },
    {
        "salt_name": "Iodex / Analgesic Balm",
        "aliases": ["Methyl Salicylate balm"],
        "common_brands": "Iodex, Volini, Moov",
        "used_for": "Muscle pain, body ache, minor sprains, congestion (topical)",
        "category": "Topical pain relief",
        "timing": "Apply externally, gently massage; do not ingest",
        "avoid": "Do not apply on broken skin or near eyes. Not for internal use.",
        "precautions": "Discontinue if skin irritation occurs.",
        "home_remedy": "Warm water fomentation, steam inhalation for congestion",
    },
]
